### Listar carros
GET http://localhost:5106/api/carros

### Buscar carro pelo ID
GET http://localhost:5106/api/carros/4

### Cadastrar carros
POST http://localhost:5106/api/carros/cadastrar
Content-Type: application/json

{
    "name": "BMW X2",
    "modelo": {
        "Id": 3
    }
}

### Alterar o carro pelo ID
PUT http://localhost:5106/api/carros/2
Content-Type: application/json

{
    "name": "BMW BMW X3"
}

### Remove o carro pelo ID
DELETE http://localhost:5106/api/carros/4

